In [55]:
%pip install ultralytics
import ultralytics
ultralytics.checks()

Ultralytics YOLOv8.0.201 🚀 Python-3.10.12 torch-2.1.0+cu118 CPU (Intel Xeon 2.20GHz)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 27.1/107.7 GB disk)


In [56]:
import numpy as np


In [57]:
from ultralytics import YOLO

In [58]:
from PIL import Image

In [59]:
model = YOLO('yolov8n.pt')
#introducing the yolov8 model

In [60]:
source = '/content/Screenshot (139).png'

#obtaining predictions
results = model(source)


image 1/1 /content/Screenshot (139).png: 640x608 1 person, 1 skateboard, 3 books, 425.3ms
Speed: 15.7ms preprocess, 425.3ms inference, 1.4ms postprocess per image at shape (1, 3, 640, 608)


In [61]:
results
#checking format of results

[ultralytics.engine.results.Results object with attributes:
 
 boxes: ultralytics.engine.results.Boxes object
 keypoints: None
 masks: None
 names: {0: 'person', 1: 'bicycle', 2: 'car', 3: 'motorcycle', 4: 'airplane', 5: 'bus', 6: 'train', 7: 'truck', 8: 'boat', 9: 'traffic light', 10: 'fire hydrant', 11: 'stop sign', 12: 'parking meter', 13: 'bench', 14: 'bird', 15: 'cat', 16: 'dog', 17: 'horse', 18: 'sheep', 19: 'cow', 20: 'elephant', 21: 'bear', 22: 'zebra', 23: 'giraffe', 24: 'backpack', 25: 'umbrella', 26: 'handbag', 27: 'tie', 28: 'suitcase', 29: 'frisbee', 30: 'skis', 31: 'snowboard', 32: 'sports ball', 33: 'kite', 34: 'baseball bat', 35: 'baseball glove', 36: 'skateboard', 37: 'surfboard', 38: 'tennis racket', 39: 'bottle', 40: 'wine glass', 41: 'cup', 42: 'fork', 43: 'knife', 44: 'spoon', 45: 'bowl', 46: 'banana', 47: 'apple', 48: 'sandwich', 49: 'orange', 50: 'broccoli', 51: 'carrot', 52: 'hot dog', 53: 'pizza', 54: 'donut', 55: 'cake', 56: 'chair', 57: 'couch', 58: 'potted p

In [62]:
for r in results:
  print(r.boxes.xyxy)
  #checking format

tensor([[ 87.6174, 276.0722, 139.8553, 376.9735],
        [ 82.0982, 371.3623, 138.6692, 383.3801],
        [119.9627,  73.1028, 287.6582, 381.3176],
        [ 54.7913,  42.2686, 218.0958, 382.3897],
        [119.7524,  69.5035, 232.2174, 383.2898]])


In [63]:
for r in results:
    im_array = r.plot()  # plotting a BGR numpy array of predictions
    im = Image.fromarray(im_array[..., ::-1])  # RGB PIL image
    im.show()  # showing image
    im.save('results4.jpg')

In [65]:
best_box = None
best_score = 0

# Class ID for 'book'
book_class_id = 73
for r in results:
  bounding_boxes = r.boxes.xyxy
  confidences = r.boxes.conf
  class_ids = r.boxes.cls

# Iterating through the detected objects
for i, box in enumerate(bounding_boxes):
    x1, y1, x2, y2 = box
    print(box)
    confidence = confidences[i]
    class_id = class_ids[i]

    if int(class_id) == book_class_id and confidence > best_score:
        best_box = (x1, y1, x2, y2)
        best_score = confidence

#now that we've detected the best box, we use it as a representative box for all books in the image
x1, y1, x2, y2 = best_box
print(best_box)
x1, y1, x2, y2 = float(best_box[0]), float(best_box[1]), float(best_box[2]), float(best_box[3])
angle = np.arctan2(y2 - y1, x2 - x1) * 180 / np.pi
#setting a threshold value of angle above which 90 is given as output
#this was decided via trial and error

if angle>75:
  inclined_angle=90
else:
  inclined_angle=angle



print(f"Inclination Angle: {inclined_angle} degrees")



tensor([ 87.6174, 276.0722, 139.8553, 376.9735])
tensor([ 82.0982, 371.3623, 138.6692, 383.3801])
tensor([119.9627,  73.1028, 287.6582, 381.3176])
tensor([ 54.7913,  42.2686, 218.0958, 382.3897])
tensor([119.7524,  69.5035, 232.2174, 383.2898])
(tensor(119.9627), tensor(73.1028), tensor(287.6582), tensor(381.3176))
Inclination Angle: 61.44997829370224 degrees
